mst:
    # image: mstracker/mst
    image: mstracker/mst:staging
    links:
        - "mongo:mongo"
        - "redis:redis"
    ports:
        # development
        - "3030:3030"
        # production
        # - "8000:8000"
    environment: 
        # for development 
        - NODE_ENV=development
        # for production
        # NODE_ENV=production
    volumes:
        - ./etc/mst/local.json:/src/config/local.json
        - ./data/capture:/src/capture
    restart: always
        
mongo:
    image: mvertes/alpine-mongo 
    volumes:
        - ./data/db:/data/db
    restart: always

redis: 
    image: redis:3-alpine
    restart: always
